export const ON_FETCH_LIVE_RATES_STARTED = 'ON_FETCH_LIVE_RATES_STARTED';
export const ON_FETCH_LIVE_RATES_SUCCEEDED = 'ON_FETCH_LIVE_RATES_SUCCEEDED';
export const ON_FETCH_LIVE_RATES_FAILED = 'ON_FETCH_LIVE_RATES_FAILED';