export const ON_FETCH_PRODUCT_STARTED = 'ON_FETCH_PRODUCT_STARTED'
export const ON_FETCH_PRODUCT_SUCCEEDED = 'ON_FETCH_PRODUCT_SUCCEEDED'
export const ON_FETCH_PRODUCT_FAILED = 'ON_FETCH_PRODUCT_FAILED'

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const TOGGLE_CART = 'TOGGLE_CART'

export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART'

export const GET_CLIENT = 'GET_CLIENT'
