export const ON_FETCH_PRODUCT_STARTED = 'ON_FETCH_PRODUCT_STARTED'
export const ON_FETCH_PRODUCT_SUCCEEDED = 'ON_FETCH_PRODUCT_SUCCEEDED'
export const ON_FETCH_PRODUCT_FAILED = 'ON_FETCH_PRODUCT_FAILED'

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const TOGGLE_CART = 'TOGGLE_CART'
export const ACTIVE_ADMIN_MODE = 'ACTIVE_ADMIN_MODE'
export const TOGGLE_MODAL_ADMIN = 'TOGGLE_MODAL_ADMIN'

export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART'
export const UPDATE_PRICE = 'UPDATE_PRICE'

export const GET_CLIENT = 'GET_CLIENT'
export const GET_PAIEMENT = 'GET_PAIEMENT'
